/**
 * Constitution Generator
 *
 * Generates .groot/constitution.md from curriculum metadata.
 * The constitution defines project principles for AI coding assistants.
 */

import { writeFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import { dirname } from 'path';
import { Curriculum, TemplateType, ConstitutionConfig } from '../types';
import { getConstitutionPath } from './paths';

export interface ConstitutionOptions {
  curriculum: Curriculum;
  templateType: TemplateType;
  outputDir: string;
}

/**
 * Generate constitution content from curriculum metadata
 */
export function generateConstitution(options: ConstitutionOptions): string {
  const { curriculum, templateType } = options;
  const config = deriveConstitutionConfig(curriculum, templateType);

  return `# Project Constitution

> Auto-generated by GROOT from curriculum configuration.
> This document defines project standards for AI coding assistants.

## Project Overview

- **Curriculum**: ${curriculum.title}
- **Topic**: ${curriculum.topic}
- **Language**: ${config.language}
- **Difficulty**: ${config.difficulty}
- **Target Audience**: ${curriculum.metadata.targetAudience}

## Coding Standards

${config.codingStandards.map((s, i) => `${i + 1}. ${s}`).join('\n')}

## Test-First Development

This project follows Test-Driven Development (TDD) principles:

1. Tests are provided and define expected behavior
2. Implement source code to make existing tests pass
3. Do NOT modify test files unless explicitly instructed
4. Run tests frequently: \`${config.testCommand}\`

## Project Structure

\`\`\`
${getProjectStructure(templateType)}
\`\`\`

## Implementation Rules

1. **Preserve Existing Structure**: Keep class names, function names, and factory functions exactly as stubbed
2. **No External Dependencies**: ${config.restrictions.join('; ')}
3. **Complete TODO Items**: Implement all TODO comments in source stubs
4. **Educational Code**: Write clear, well-commented code that teaches concepts
5. **Self-Contained Deliverables**: Each deliverable is independent in its own source file

## Language-Specific Guidelines

${getLanguageGuidelines(templateType)}

## Phase Guidelines

${curriculum.phases.map(phase => `### Phase ${phase.number}: ${phase.title}

${phase.description}

**Key Concepts**: ${phase.keyConcepts.map(kc => kc.term).join(', ')}
`).join('\n')}

## Acceptance Criteria Format

Each deliverable has acceptance criteria that define "done":

- Criteria are testable conditions
- All criteria must be satisfied for completion
- Tests verify criteria automatically via \`groot check\`

## AI Assistant Instructions

When implementing code for this project:

1. Read the spec.md for the deliverable to understand requirements
2. Review plan.md for the suggested implementation approach
3. Follow tasks.md as a step-by-step checklist
4. Run tests after each significant change
5. Ask for clarification if requirements are unclear
6. Keep implementations simple and educational
`;
}

/**
 * Derive constitution config from curriculum
 */
function deriveConstitutionConfig(
  curriculum: Curriculum,
  templateType: TemplateType
): ConstitutionConfig {
  const languageConfig = getLanguageConfig(templateType);

  return {
    projectName: curriculum.title,
    topic: curriculum.topic,
    language: templateType,
    difficulty: curriculum.metadata.difficulty,
    codingStandards: [
      `Use ONLY the ${languageConfig.name} standard library — no external dependencies`,
      languageConfig.styleGuide,
      'Include meaningful comments explaining implementation logic',
      `Follow ${languageConfig.name}-idiomatic naming conventions`,
      'Keep functions focused and reasonably sized',
      'Handle edge cases gracefully',
    ],
    testFramework: languageConfig.testFramework,
    testCommand: languageConfig.testCommand,
    restrictions: [
      'No pip install or npm install required',
      'Standard library only',
      'No network calls unless explicitly required by the deliverable',
    ],
  };
}

/**
 * Get language-specific configuration
 */
function getLanguageConfig(templateType: TemplateType): {
  name: string;
  styleGuide: string;
  testFramework: string;
  testCommand: string;
} {
  switch (templateType) {
    case 'python':
      return {
        name: 'Python',
        styleGuide: 'Follow PEP 8 style guidelines',
        testFramework: 'pytest',
        testCommand: 'python3 -m pytest -v',
      };
    case 'typescript':
      return {
        name: 'TypeScript',
        styleGuide: 'Use strict TypeScript (avoid `any` types)',
        testFramework: 'Jest',
        testCommand: 'npm test',
      };
    case 'javascript':
      return {
        name: 'JavaScript',
        styleGuide: 'Use modern ES6+ syntax',
        testFramework: 'Jest',
        testCommand: 'npm test',
      };
    case 'react':
      return {
        name: 'React/TypeScript',
        styleGuide: 'Use functional components with hooks',
        testFramework: 'Vitest',
        testCommand: 'npm test',
      };
    case 'vue':
      return {
        name: 'Vue/TypeScript',
        styleGuide: 'Use Composition API with TypeScript',
        testFramework: 'Vitest',
        testCommand: 'npm test',
      };
    default:
      return {
        name: templateType,
        styleGuide: 'Follow language best practices',
        testFramework: 'configured test runner',
        testCommand: 'npm test',
      };
  }
}

/**
 * Get project structure diagram for template type
 */
function getProjectStructure(templateType: TemplateType): string {
  switch (templateType) {
    case 'python':
      return `project/
├── .groot/
│   ├── curriculum.json
│   └── constitution.md
├── specs/
│   └── phase-N/
│       └── deliverable-name/
│           ├── spec.md
│           ├── plan.md
│           └── tasks.md
├── src/
│   ├── __init__.py
│   └── deliverable_name.py
├── tests/
│   ├── __init__.py
│   └── test_deliverable_name.py
├── requirements.txt
└── pytest.ini`;
    case 'typescript':
    case 'javascript':
      return `project/
├── .groot/
│   ├── curriculum.json
│   └── constitution.md
├── specs/
│   └── phase-N/
│       └── deliverable-name/
│           ├── spec.md
│           ├── plan.md
│           └── tasks.md
├── src/
│   └── deliverable-name.ts
├── tests/
│   └── deliverable-name.test.ts
├── package.json
└── tsconfig.json`;
    default:
      return `project/
├── .groot/
│   ├── curriculum.json
│   └── constitution.md
├── specs/
│   └── phase-N/
│       └── deliverable-name/
│           ├── spec.md
│           ├── plan.md
│           └── tasks.md
├── src/
└── tests/`;
  }
}

/**
 * Get language-specific guidelines
 */
function getLanguageGuidelines(templateType: TemplateType): string {
  switch (templateType) {
    case 'python':
      return `### Python

- Use type hints on all function signatures
- Include docstrings for all classes and public methods
- Use \`snake_case\` for functions and variables
- Use \`PascalCase\` for class names
- Import from \`src.\` package prefix (e.g., \`from src.module import Class\`)
- Never nest triple-quoted strings (\`'''\` inside \`'''\`)`;
    case 'typescript':
      return `### TypeScript

- Enable strict mode in tsconfig.json
- Prefer interfaces over type aliases for object shapes
- Use \`camelCase\` for functions and variables
- Use \`PascalCase\` for classes and interfaces
- Export types alongside implementations
- Avoid \`any\` — use \`unknown\` if type is truly unknown`;
    case 'javascript':
      return `### JavaScript

- Use modern ES6+ features (const, let, arrow functions)
- Use JSDoc comments for type documentation
- Use \`camelCase\` for functions and variables
- Use \`PascalCase\` for classes
- Prefer async/await over raw Promises`;
    case 'react':
      return `### React/TypeScript

- Use functional components with hooks
- Define prop types with TypeScript interfaces
- Use \`useState\`, \`useEffect\`, \`useMemo\` appropriately
- Keep components focused (single responsibility)
- Extract reusable logic into custom hooks`;
    case 'vue':
      return `### Vue/TypeScript

- Use Composition API with \`<script setup>\`
- Define props and emits with TypeScript
- Use \`ref\`, \`reactive\`, \`computed\` appropriately
- Keep components focused
- Use composables for reusable logic`;
    default:
      return `### ${templateType}

- Follow language-specific best practices
- Write clear, self-documenting code
- Include comments for complex logic`;
  }
}

/**
 * Write constitution to file
 */
export async function writeConstitution(options: ConstitutionOptions): Promise<string> {
  const content = generateConstitution(options);
  const constitutionPath = getConstitutionPath(options.outputDir);

  // Ensure .groot directory exists
  const dir = dirname(constitutionPath);
  if (!existsSync(dir)) {
    await mkdir(dir, { recursive: true });
  }

  await writeFile(constitutionPath, content, 'utf-8');
  return constitutionPath;
}
