/**
 * Curriculum Output
 *
 * Handles formatting and writing curricula to markdown and JSON
 */

import { writeFile } from 'fs/promises';
import { Curriculum, GROWTH_STAGE_ICONS } from '../types';

/**
 * Convert curriculum to markdown format
 */
export function formatCurriculumMarkdown(curriculum: unknown): string {
  const c = curriculum as Curriculum;

  let md = '';

  // Header
  md += `# ${c.title}\n\n`;
  md += `> ${c.description}\n\n`;

  // Metadata
  md += `## 📊 Overview\n\n`;
  md += `- **Topic**: ${c.topic}\n`;
  md += `- **Difficulty**: ${c.metadata.difficulty.charAt(0).toUpperCase() + c.metadata.difficulty.slice(1)}\n`;
  md += `- **Estimated Time**: ${c.metadata.estimatedHours} hours\n`;
  md += `- **Target Audience**: ${c.metadata.targetAudience}\n`;

  if (c.metadata.prerequisites.length > 0) {
    md += `- **Prerequisites**:\n`;
    c.metadata.prerequisites.forEach(prereq => {
      md += `  - ${prereq}\n`;
    });
  }

  md += `\n`;

  // Phases summary
  md += `## 🌳 Learning Journey\n\n`;
  md += `| # | Phase | Growth Stage | Hours |\n`;
  md += `|---|-------|--------------|-------|\n`;
  c.phases.forEach(phase => {
    const icon = GROWTH_STAGE_ICONS[phase.growthStage];
    md += `| ${phase.number} | ${phase.title} | ${icon} ${phase.growthStage} | ${phase.estimatedHours}h |\n`;
  });
  md += `\n`;

  // Detailed phases
  c.phases.forEach(phase => {
    md += `---\n\n`;
    md += `## Phase ${phase.number}: ${phase.title}\n\n`;
    md += `**${GROWTH_STAGE_ICONS[phase.growthStage]} Growth Stage**: ${phase.growthStage.charAt(0).toUpperCase() + phase.growthStage.slice(1)}\n\n`;
    md += `**Duration**: ${phase.estimatedHours} hours\n\n`;
    md += `${phase.description}\n\n`;

    // Objectives
    md += `### 🎯 Learning Objectives\n\n`;
    phase.objectives.forEach((obj, idx) => {
      md += `${idx + 1}. ${obj.description}\n`;
    });
    md += `\n`;

    // Deliverables
    md += `### 📦 Deliverables\n\n`;
    phase.deliverables.forEach(del => {
      md += `#### ${del.title}\n\n`;
      md += `${del.description}\n\n`;
      md += `**Acceptance Criteria:**\n`;
      del.acceptanceCriteria.forEach(criteria => {
        md += `- [ ] ${criteria}\n`;
      });
      md += `\n`;
    });

    // Key Concepts
    if (phase.keyConcepts.length > 0) {
      md += `### 🔑 Key Concepts\n\n`;
      phase.keyConcepts.forEach(concept => {
        md += `**${concept.term}**: ${concept.definition}\n\n`;
      });
    }
  });

  // Footer
  md += `---\n\n`;
  md += `*Generated by GROOT - Guided Resource for Organized Objective Training*\n`;
  md += `*"We are Groot." — We grow together.*\n`;

  return md;
}

/**
 * Write curriculum as markdown file
 */
export async function writeCurriculumMarkdown(curriculum: unknown, filePath: string): Promise<void> {
  const markdown = formatCurriculumMarkdown(curriculum);
  await writeFile(filePath, markdown, 'utf-8');
}

/**
 * Write curriculum as JSON file
 */
export async function writeCurriculumJSON(curriculum: unknown, filePath: string): Promise<void> {
  const json = JSON.stringify(curriculum, null, 2);
  await writeFile(filePath, json, 'utf-8');
}

/**
 * Format curriculum as JSON string
 */
export function formatCurriculumJSON(curriculum: unknown): string {
  return JSON.stringify(curriculum, null, 2);
}
